export const CardName : string[] = ['迪迦奥特曼','北冰洋','猫鼠游戏','肖申克的救赎','蜘蛛侠','让子弹飞','钢铁侠','大圣归来']
export const CardSource : string[] = ['app.media.dijia','app.media.bby','app.media.maoshuyouxi','app.media.xiaoshenke','app.media.zzx',
  'app.media.rzdf','app.media.gtx','app.media.dagl']
export const CardName2 : string[] = ['迪迦奥特曼','蜘蛛侠','北冰洋','猫鼠游戏','夏洛特烦恼','肖申克的救赎','蜘蛛侠','让子弹飞','钢铁侠','大圣归来','雨中曲','楚门的世界']
export const CardSource2 : string[] = ['app.media.dijia','app.media.zzx2','app.media.bby','app.media.maoshuyouxi','app.media.xltfn','app.media.xiaoshenke','app.media.zzx',
  'app.media.rzdf','app.media.gtx','app.media.dagl','app.media.yzq','app.media.cmdsj']